<?xml version="1.0"?>
<package format="3">
  <name>pro450_description</name>
  <version>0.1.0</version>
  <description>Independent myCobot Pro 450 and MyGripper F100 robot description.</description>
  <maintainer email="han1284@example.com">han1284</maintainer>
  <license>BSD-3-Clause</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>realsense2_description</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
